# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: MainJob
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
    displayName: 'Install Node.js'
  - script: |
      node -v
      npm -v
    displayName: display version

- job: Test
  dependsOn: MainJob
  variables:
    JH_REPO: $BUILD_REPOSITORY_URI
    DISPLAY: :99.9
  strategy:
    maxParallel: 2
    matrix: 
      alpha:
        message: alpha
      beta:
        message: beta
  steps:
  - script: |
      node -v
      npm -v
    displayName: display version
  - script: echo $message
    displayName: display message
