# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

jobs:
- job: Test
  strategy:
    maxParallel: 2
    matrix: 
      alpha:
        message: alpha
      beta:
        message: beta

  steps:
  - script: echo $message
    displayName: 'Display message variable'
  - script: |
      java -version
      node -v
      npm -v
      docker version
      docker-compose version
    displayName: 'Check installed tools'
  - script: |
      sudo npm install -g npm
      npm -v
    displayName: 'Update NPM'
  - script: npm install
  - script: ./mvnw test
    displayName: 'Backend Tests'
  - script: npm test -- -u
    displayName: 'Frontend Tests'
  - script: echo 'end'
