# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    TOTO: toto
    TOTO_CONCAT: $(TOTO)hello
    JHIPSTER_HOME: $(pwd)
    JHIPSTER_TRAVIS: $(pwd)/test-integration
    JHIPSTER_SAMPLES: $(JHIPSTER_TRAVIS)/samples
    JHIPSTER_SCRIPTS: $(JHIPSTER_TRAVIS)/scripts

  strategy:
    maxParallel: 2
    matrix: 
      alpha:
        message: alpha
      beta:
        message: beta

  steps:
  - script: echo $(message)
    displayName: 'Display message variable'
  - script: |
      pwd
      echo AGENT_HOMEDIRECTORY=$AGENT_HOMEDIRECTORY
      echo TOTO=$(TOTO)
      echo TOTO_CONCAT=$(TOTO_CONCAT)
      echo JHIPSTER_HOME=$(JHIPSTER_HOME)
      echo JHIPSTER_TRAVIS=$(JHIPSTER_TRAVIS)
      echo JHIPSTER_SAMPLES=$(JHIPSTER_SAMPLES)
      echo JHIPSTER_SCRIPTS=$(JHIPSTER_SCRIPTS)
      ls -al /home/vsts/
      ls -al /home/vsts/work/
      ls -al /home/vsts/work/1/
      ls -al $(pwd)
  - script: |
      java -version
      node -v
      npm -v
      docker version
      docker-compose version
    displayName: 'Check installed tools'
  - script: |
      sudo npm install -g npm
      npm -v
    displayName: 'Update NPM'
  - script: npm install
  - script: ./mvnw test
    displayName: 'Backend Tests'
  - script: npm test -- -u
    displayName: 'Frontend Tests'
  - script: echo 'end'
