#!/bin/bash

echo "AGENT_HOMEDIRECTORY=$AGENT_HOMEDIRECTORY"
echo "BUILD_REPOSITORY_LOCALPATH=$BUILD_REPOSITORY_LOCALPATH"
echo "BUILD_SOURCESDIRECTORY=$BUILD_SOURCESDIRECTORY"
echo JH_HOME=$(JH_HOME)
echo JH_INTEG=$(JH_INTEG)
echo JH_FOLDER_APP=$(JH_FOLDER_APP)
echo "JH_HOME=$(JH_HOME)"
echo "JH_INTEG=$(JH_INTEG)"
echo "JH_FOLDER_APP=$(JH_FOLDER_APP)"
