#!/bin/bash

echo "AGENT_HOMEDIRECTORY=$AGENT_HOMEDIRECTORY"
echo "BUILD_REPOSITORY_LOCALPATH=$BUILD_REPOSITORY_LOCALPATH"
echo "BUILD_SOURCESDIRECTORY=$BUILD_SOURCESDIRECTORY"
echo "JH_HOME=$JH_HOME"
echo "JH_HOME2=$JH_HOME2"
echo "JH_INTEG=$JH_INTEG"
echo "JH_SAMPLES=$JH_SAMPLES"
echo "JH_SCRIPTS=$JH_SCRIPTS"
echo "JH_SCRIPTS=$(JH_SCRIPTS)"
echo "JH_SCRIPTS=$($JH_SCRIPTS)"
echo "JH_SCRIPTS=$($(JH_SCRIPTS))"